SIM ?= icarus
TOPLEVEL_LANG := verilog
VERILOG_SOURCES := $(PWD)/rtl/mux10.sv
TOPLEVEL := mux10
COCOTB_TEST_MODULES := test_mux10
COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
